### ISSUE TITLE
p4app launch problem

### ISSUE THREAD

**Issue by technobilly** [p4lang/p4app#20]
- "Virgin" Ubuntu 16.04 VM in VirtualBox
- Docker installed, docker group created, user added to it
- Docker run hello-world - verified
- p4app git clone'd
- p4app copied to /usr/local/bin

Follow instructions:
~/p4/p4app$ p4app run examples/simple_router.p4app
Unable to find image 'p4lang/p4app:stable' locally
docker: Error response from daemon: manifest for p4lang/p4app:stable not found.

Do I need to build the initial docker image using provided Dockerfile or is this handled by p4app? 
Thanks.

**Comment by technobilly** [comment]
I looked on docker hub and discovered there is no `:stable` tag for this image, but there is a `:latest`. By examining p4app I determined you can override the default tag as follows:
```export P4APP_IMAGE=p4lang/p4app:latest
p4app run examples/simple_router.p4app```

So a `:stable` tag should be added to one of the images on docker hub, or else change the p4app script to use `:latest`, or else add instructions to the readme. Thanks.

**Comment by haazy** [comment]
Hello, 
I am also having the same issue.

sudo p4app run examples/simple_router.p4app
Unable to find image 'p4lang/p4app:stable' locally
docker: Error response from daemon: manifest for p4lang/p4app:stable not found.
See 'docker run --help'.


What can I do?  There is stable tag for the image.

Thanks
