### ISSUE TITLE
mininet xterm fails

### ISSUE THREAD

**Issue by technobilly** [p4lang/p4app#22]
I don't know if this is a general problem of running mininet inside Docker or a matter of this specific Docker image.
```
p4app run examples/simple_router.p4app
...
*** Starting CLI:
mininet> h1 ping -c 1 h2
PING 10.0.1.10 (10.0.1.10) 56(84) bytes of data.
64 bytes from 10.0.1.10: icmp_seq=1 ttl=63 time=0.600 ms

--- 10.0.1.10 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.600/0.600/0.600/0.000 ms
mininet> xterm h1
Error: Cannot connect to display
```

**Comment by robertsoule-barefoot** [comment]
This is, unfortunately, an issue with running mininet inside of Docker. One potential workaround is to redirect the output of the command to a file, and then outside of docker, tail that file. Something like:

docker exec -i -t `docker ps -lq` tail -f /tmp/h2.txt

**Comment by technobilly** [comment]
Thanks! Methinks mininet needs some enhancements since Docker is prevalent.
