### ISSUE TITLE
mininet sysctl errors

### ISSUE THREAD

**Issue by technobilly** [p4lang/p4app#23]
This appears to be a general problem running mininet inside Docker. For example see the following links:
https://github.com/moby/moby/issues/8103
https://github.com/moby/moby/issues/4717

So this bug report is more of a footnote because I'm not sure there is a remedy. The advice seems to be to make the resource settings per the mininet utils.py file inside your host before launching Docker. Then at least the errors are benign.

```
chris@t1700-vbox-ub16:~/p4/p4app$ p4app run examples/simple_router.p4app/
Entering build directory.
Extracting package.
Reading package manifest.

 p4c-bm2-ss --p4v 16 "simple_router.p4" -o "simple_router.p4.json"
> python2 "/scripts/mininet/single_switch_mininet.py" --log-file "/var/log/simple_router.p4.log" --cli-message "mininet_message.txt" --num-hosts 2 --switch-config "simple_router.config" --behavioral-exe "simple_switch" --json "simple_router.p4.json"
Adding host h1
Adding host h2
*** Error setting resource limits. Mininet's performance may be affected.
```
In short, several files inside /proc/sys/net and /proc/sys/core are unavailable inside the Docker container. 
From https://github.com/mininet/mininet/blob/master/mininet/util.py I obtained the following; fixLimits() throws the error:
```
#...
from resource import getrlimit, setrlimit, RLIMIT_NPROC, RLIMIT_NOFILE
#...
def sysctlTestAndSet( name, limit ):
    "Helper function to set sysctl limits"
    #convert non-directory names into directory names
    if '/' not in name:
        name = '/proc/sys/' + name.replace( '.', '/' )
    #read limit
    with open( name, 'r' ) as readFile:
        oldLimit = readFile.readline()
        if isinstance( limit, int ):
            #compare integer limits before overriding
            if int( oldLimit ) < limit:
                with open( name, 'w' ) as writeFile:
                    writeFile.write( "%d" % limit )
        else:
            #overwrite non-integer limits
            with open( name, 'w' ) as writeFile:
                writeFile.write( limit )

def rlimitTestAndSet( name, limit ):
    "Helper function to set rlimits"
    soft, hard = getrlimit( name )
    if soft < limit:
        hardLimit = hard if limit < hard else limit
	setrlimit( name, ( limit, hardLimit ) )

def fixLimits():
    "Fix ridiculously small resource limits."
    debug( "*** Setting resource limits\n" )
    try:
        rlimitTestAndSet( RLIMIT_NPROC, 8192 )
        rlimitTestAndSet( RLIMIT_NOFILE, 16384 )
        #Increase open file limit
        sysctlTestAndSet( 'fs.file-max', 10000 )
        #Increase network buffer space
        sysctlTestAndSet( 'net.core.wmem_max', 16777216 )
        sysctlTestAndSet( 'net.core.rmem_max', 16777216 )
        sysctlTestAndSet( 'net.ipv4.tcp_rmem', '10240 87380 16777216' )
        sysctlTestAndSet( 'net.ipv4.tcp_wmem', '10240 87380 16777216' )
        sysctlTestAndSet( 'net.core.netdev_max_backlog', 5000 )
        #Increase arp cache size
        sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh1', 4096 )
        sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh2', 8192 )
        sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh3', 16384 )
        #Increase routing table size
        sysctlTestAndSet( 'net.ipv4.route.max_size', 32768 )
        #Increase number of PTYs for nodes
        sysctlTestAndSet( 'kernel.pty.max', 20000 )
    # pylint: disable=broad-except
    except Exception:
        warn( "*** Error setting resource limits. "
              "Mininet's performance may be affected.\n" )
```

If you try to execute the above settings you can easily see which ones fail:
```
>>> rlimitTestAndSet( RLIMIT_NPROC, 8192 )
>>> rlimitTestAndSet( RLIMIT_NOFILE, 16384 )
>>> sysctlTestAndSet( 'fs.file-max', 10000 )
>>> sysctlTestAndSet( 'net.core.wmem_max', 16777216 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/core/wmem_max'
>>> sysctlTestAndSet( 'net.core.rmem_max', 16777216 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/core/rmem_max'
>>> sysctlTestAndSet( 'net.ipv4.tcp_rmem', '10240 87380 16777216' )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/ipv4/tcp_rmem'
>>> sysctlTestAndSet( 'net.ipv4.tcp_wmem', '10240 87380 16777216' )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/ipv4/tcp_wmem'
>>> sysctlTestAndSet( 'net.core.netdev_max_backlog', 5000 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/core/netdev_max_backlog'
>>> sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh1', 4096 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/ipv4/neigh/default/gc_thresh1'
>>> sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh2', 8192 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/ipv4/neigh/default/gc_thresh2'
>>> sysctlTestAndSet( 'net.ipv4.neigh.default.gc_thresh3', 16384 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/ipv4/neigh/default/gc_thresh3'
>>> sysctlTestAndSet( 'net.ipv4.route.max_size', 32768 )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in sysctlTestAndSet
IOError: [Errno 2] No such file or directory: '/proc/sys/net/ipv4/route/max_size'
>>> sysctlTestAndSet( 'kernel.pty.max', 20000 )
```

**Comment by haazy** [comment]
Hello, 
I am new to p4.

I tried to run  sudo p4app run examples/simple_router.p4app and i got below error
Unable to find image 'p4lang/p4app:stable' locally
docker: Error response from daemon: manifest for p4lang/p4app:stable not found.
See 'docker run --help'.

but my docker seems to be fine because I get success message when I run this 
sudo docker run hello-world

Kindly help

**Comment by technobilly** [comment]
If I recall, changing the Dockerfile to require "p4lang/p4app:latest" will fix it. This really should be fixed.

**Comment by haazy** [comment]
Thanks so much for your response. I changed it to latest and it worked.

You're appreciated

**Comment by bakkarol** [comment]
Hi! 

i have problems while running multiswitch.p4app. App starts and 
and stops just after. Am i able to run it like simple_router.p4app and make some changes in topology?

`
$ sudo p4app run multiswitch.p4app
Entering build directory.
Extracting package.
Reading package manifest.
> p4c-bm2-ss --p4v 16 "simple_router.p4" -o "simple_router.p4.json"
> python2 "/scripts/mininet/multi_switch_mininet.py" --log-dir "/tmp/p4app_logs" --manifest "./p4app.json" --target "multiswitch" --auto-control-plane --behavioral-exe "simple_switch" --json "simple_router.p4.json"
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 s2 
*** Adding links:
(0ms delay) (0ms delay) (h1, s1) (50ms delay) (50ms delay) (h2, s2) (0ms delay) (0ms delay) (s1, s2) 
*** Configuring hosts
h1 h2 
*** Starting controller

*** Starting 2 switches
s1 Starting P4 switch s1.
simple_switch -i 1@s1-eth1 -i 2@s1-eth2 --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 simple_router.p4.json
P4 switch s1 has been started.
s2 Starting P4 switch s2.
simple_switch -i 1@s2-eth1 -i 2@s2-eth2 --thrift-port 9091 --nanolog ipc:///tmp/bm-1-log.ipc --device-id 1 simple_router.p4.json
P4 switch s2 has been started.

table_set_default send_frame _drop
table_set_default forward _drop
table_set_default ipv4_lpm _drop
table_add send_frame rewrite_mac 1 => 00:aa:00:02:00:02
table_add forward set_dmac 10.0.2.101 => 00:04:00:00:02:01
table_add ipv4_lpm set_nhop 10.0.2.101/32 => 10.0.2.101 1
table_add send_frame rewrite_mac 2 => 00:aa:00:02:01:00
table_add forward set_dmac 10.0.1.101 => 00:aa:00:01:02:00
table_add ipv4_lpm set_nhop 10.0.1.101/32 => 10.0.1.101 2
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: Setting default action of send_frame
action:              _drop
runtime data:        
RuntimeCmd: Setting default action of forward
action:              _drop
runtime data:        
RuntimeCmd: Setting default action of ipv4_lpm
action:              _drop
runtime data:        
RuntimeCmd: Adding entry to exact match table send_frame
match key:           EXACT-00:01
action:              rewrite_mac
runtime data:        00:aa:00:02:00:02
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table forward
match key:           EXACT-0a:00:02:65
action:              set_dmac
runtime data:        00:04:00:00:02:01
Entry has been added with handle 0
RuntimeCmd: Adding entry to lpm match table ipv4_lpm
match key:           LPM-0a:00:02:65/32
action:              set_nhop
runtime data:        0a:00:02:65	00:01
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table send_frame
match key:           EXACT-00:02
action:              rewrite_mac
runtime data:        00:aa:00:02:01:00
Entry has been added with handle 1
RuntimeCmd: Adding entry to exact match table forward
match key:           EXACT-0a:00:01:65
action:              set_dmac
runtime data:        00:aa:00:01:02:00
Entry has been added with handle 1
RuntimeCmd: Adding entry to lpm match table ipv4_lpm
match key:           LPM-0a:00:01:65/32
action:              set_nhop
runtime data:        0a:00:01:65	00:02
Entry has been added with handle 1
RuntimeCmd: 

table_set_default send_frame _drop
table_set_default forward _drop
table_set_default ipv4_lpm _drop
table_add send_frame rewrite_mac 1 => 00:aa:00:01:00:01
table_add forward set_dmac 10.0.1.101 => 00:04:00:00:01:01
table_add ipv4_lpm set_nhop 10.0.1.101/32 => 10.0.1.101 1
table_add send_frame rewrite_mac 2 => 00:aa:00:01:02:00
table_add forward set_dmac 10.0.2.101 => 00:aa:00:02:01:00
table_add ipv4_lpm set_nhop 10.0.2.101/32 => 10.0.2.101 2
Obtaining JSON from switch...
Done
Control utility for runtime P4 table manipulation
RuntimeCmd: Setting default action of send_frame
action:              _drop
runtime data:        
RuntimeCmd: Setting default action of forward
action:              _drop
runtime data:        
RuntimeCmd: Setting default action of ipv4_lpm
action:              _drop
runtime data:        
RuntimeCmd: Adding entry to exact match table send_frame
match key:           EXACT-00:01
action:              rewrite_mac
runtime data:        00:aa:00:01:00:01
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table forward
match key:           EXACT-0a:00:01:65
action:              set_dmac
runtime data:        00:04:00:00:01:01
Entry has been added with handle 0
RuntimeCmd: Adding entry to lpm match table ipv4_lpm
match key:           LPM-0a:00:01:65/32
action:              set_nhop
runtime data:        0a:00:01:65	00:01
Entry has been added with handle 0
RuntimeCmd: Adding entry to exact match table send_frame
match key:           EXACT-00:02
action:              rewrite_mac
runtime data:        00:aa:00:01:02:00
Entry has been added with handle 1
RuntimeCmd: Adding entry to exact match table forward
match key:           EXACT-0a:00:02:65
action:              set_dmac
runtime data:        00:aa:00:02:01:00
Entry has been added with handle 1
RuntimeCmd: Adding entry to lpm match table ipv4_lpm
match key:           LPM-0a:00:02:65/32
action:              set_nhop
runtime data:        0a:00:02:65	00:02
Entry has been added with handle 1
RuntimeCmd: 

**********
Network configuration for: h1
Default interface: h1-eth0	10.0.0.1	00:04:00:00:01:01
**********
**********
Network configuration for: h2
Default interface: h2-eth0	10.0.0.2	00:04:00:00:02:01
**********
port: 8000
echo_msg: foobar

h1 python echo_server.py $port
h2 python echo_client.py 10.0.1.101 $port $echo_msg
(None, '')
(None, '')
*** Stopping 0 controllers

*** Stopping 3 links
...
*** Stopping 2 switches
s1 s2 
*** Stopping 2 hosts
h1 h2 
*** Done
`

**Comment by soreana** [comment]
This issue by could be fixed by sharing host network parameters. Check [here](https://github.com/soreana/docker-mininet/blob/master/docker-compose.yml) for complete docker-compose.yml
