### ISSUE TITLE
xterm not working in mininet CLI with p4app

### ISSUE THREAD

**Issue by V02460** [p4lang/p4app#26]
After starting a mininet CLI with p4app it’s not possible to run xterm on a host.

    $ sudo p4app run examples/simple_router.p4app

    [...]

    mininet> xterm h1
    Error: Cannot connect to display

**Comment by robertsoule-barefoot** [comment]
This is a known issue with running X inside of docker, and there really isn't a good fix. The workaround is to write the output from commands executed on h1 to a file, use the docker exec command to tail that file.

**Comment by fattaholmanan** [comment]
I had the same problem, this helped me resolve the problem:
[solutions-for-low-screen-resolution-in-ubuntu](http://linuxbsdos.com/2014/10/31/solutions-for-low-screen-resolution-in-ubuntu-14-0414-10-and-virtualbox/)

>  Use Xdiagnose From the Dash, search for and launch Xdiagnose, then enable all the options under the Debug section. Click the Apply button, then close the window and restart the system. You’ll have to restart. Logging out, then in won’t do.

**Comment by theojepsen** [comment]
@V02460 with PR #38 you can now open a new terminal on a Mininet host. Once the p4app is running, open a new terminal, and execute:
```
p4app exec m h1 bash
```
You will now have a shell on `h1`.
