### ISSUE TITLE
custom topology with mininet for multiple l2switch 

### ISSUE THREAD

**Issue by omeshF** [p4lang/p4app#33]
I'm currently trying to implement a custom topology and my code is as follows. Although it doesn't generate any errors , hosts doesn't seem to start up. Any help you could provide will be greatly appreciated. Thank you in advance

```
class SingleSwitchTopo(Topo):
    "Single switch connected to n (< 256) hosts."
    def __init__(self, sw_path, json_path, thrift_port, pcap_dump, n, **opts):
        # Initialize topology and default options
        Topo.__init__(self, **opts)

        switch = self.addSwitch('s1',
                                sw_path = sw_path,
                                json_path = json_path,
                                thrift_port = thrift_port,
                                pcap_dump = pcap_dump)
	switch2 = self.addSwitch('s2',
                                sw_path = sw_path,
                                json_path = json_path,
                                thrift_port = thrift_port,
                                pcap_dump = pcap_dump)
	switch3 = self.addSwitch('s3',
                                sw_path = sw_path,
                                json_path = json_path,
                                thrift_port = thrift_port,
                                pcap_dump = pcap_dump)
	
        for h in xrange(n):
            host = self.addHost('h%d' % (h + 1),
                                ip = "10.0.%d.10/24" % h,
                                mac = '00:04:00:00:00:%02x' %h)
	    
	    host2 = self.addHost('h%d' % (h + 1),
                                ip = "10.0.%d.10/24" % h,
                                mac = '00:04:00:00:00:%02x' %h)
	    host3 = self.addHost('h%d' % (h + 1),
                                ip = "10.0.%d.10/24" % h,
                                mac = '00:04:00:00:00:%02x' %h)
	    host4 = self.addHost('h%d' % (h + 1),
                                ip = "10.0.%d.10/24" % h,
                                mac = '00:04:00:00:00:%02x' %h)
	    host5 = self.addHost('h%d' % (h + 1),
                                ip = "10.0.%d.10/24" % h,
                                mac = '00:04:00:00:00:%02x' %h)
	    host6 = self.addHost('h%d' % (h + 1),
                                ip = "10.0.%d.10/24" % h,
                                mac = '00:04:00:00:00:%02x' %h)

            self.addLink(host, switch)
	    self.addLink(switch, switch2)
	    self.addLink(switch2, host2)
	    self.addLink(switch2, host3)
	    self.addLink(switch2, host4)
	    self.addLink(switch1, switch3)
	    self.addLink(switch3, host5)
	    self.addLink(switch3, host6)

def main():
    num_hosts = args.num_hosts
    mode = args.mode

    topo = SingleSwitchTopo(args.behavioral_exe,
                            args.json,
                            args.thrift_port,
                            args.pcap_dump,
                            num_hosts)
    net = Mininet(topo = topo,
                  host = P4Host,
                  switch = P4Switch,
                  controller = None)
    net.start()


    sw_mac = ["00:aa:bb:00:00:%02x" % n for n in xrange(num_hosts)]

    sw_addr = ["10.0.%d.1" % n for n in xrange(num_hosts)]

    for n in xrange(num_hosts):
        h = net.get('h%d' % (n + 1))
        if mode == "l2":
            h.setDefaultRoute("dev eth0")
        else:
            h.setARP(sw_addr[n], sw_mac[n])
            h.setDefaultRoute("dev eth0 via %s" % sw_addr[n])

    for n in xrange(num_hosts):
        h = net.get('h%d' % (n + 1))
        h.describe()

    sleep(1)

    print "Ready !"

    CLI( net )
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    main()
```

**Comment by robertsoule-barefoot** [comment]
From the mininet command prompt, if you type:

mininet> nodes

what do you see?

**Comment by omeshF** [comment]
Hi @robertsoule-barefoot 

Thank you for your response. Please find this is the prompt I get 

mininet> nodes
available nodes are: 
h1 h2 h3 h4 h5 h6 h7 s1 s2 s3

Awaiting a response at your earliest

Thank you 

Omesh

**Comment by robertsoule-barefoot** [comment]
From the output of the command, it appears that there are, in fact, 7 hosts running in Mininet (h1-h7). You should be able to try things execute commands on hosts from the mining command line (e.g., mininet> h1 ls) and see the results. If the network is configured correctly, you could send traffic between hosts (mininet> h1 ping h2).

Note that Mininet won't start a terminal window on every host. And, from within the docker container, it is not easy to launch terminal windows from within Mininet in the docker container. There are some relatively heavyweight solutions, such as forwarding X11 over SSH and running a VNC client. But, it would probably be easier to install all the software in a VM at that point.

**Comment by omeshF** [comment]
Hi @robertsoule-barefoot 
Thank you for your quick response. When mininet > h1 ls I can see an exact version of the Host computer. But I believe the problem may lie on receiving the following error when ifconfig eth0 up on h2 ,h3...h7 is passed. 

eth0: ERROR while getting interface flags: No such device

I have tried the conventional methods to solve this . Any suggestions you could provide will be deeply appreciated. 

Thank you
Omesh

**Comment by robertsoule-barefoot** [comment]
I'm afraid I don't understand what problem you're trying to solve. Why are you running ifconfig on the hosts? That may interfere with Mininet.

**Comment by omeshF** [comment]
Hi , Thank you for your response. I want to simulate the following topology. 
h1 h2 h3 - s1 -s2 - s3 - h4 h5 h6

Any assistance would be greatly appreciated
Thank you

**Comment by theojepsen** [comment]
Hi @omeshF ,

Are you trying to connect the hosts directly to eachother? i.e. h1 <-> h2 <-> h3 <-> s1 <-> s2 etc.?
If so, that is not currently supported. Hosts cannot be connected directly to each other. Hosts can only be connected to switches.

**Comment by omeshF** [comment]
Hi @theojepsen 
I want to connect Hosts to the switch. Sorry if the illustration wasn't clear. 
no summarize h1<->s1<->s2<->s3<->h2

Thank you

**Comment by theojepsen** [comment]
For the topology

    h1<->s1<->s2<->s3<->h2

simply edit the `links` variable of `p4app.json` like this:

```javascript
"links": [["h1", "s1"], ["s1", "s2"], ["s2", "s3"], ["s3", "h2"]],
```
