### ISSUE TITLE
MultiSwitch - Command reformatting replaces host names with IP address of substrings

### ISSUE THREAD

**Issue by Healesj** [p4lang/p4app#44]
When using more than 9 hosts names h1,h2, ...etc the command reformatting replaces h11 with (ip for h1)1 
for example : 
"h1":{
"cmd": "IP_for_h_1 h1",
"startup_sleep": 1,
"wait":true
},"h11":{
"cmd": "IP for h_11 h11",
"startup_sleep": 1,
"wait":true

the 2 commands are reformatted to : "IP_for_h_1 10.0.1.101" and "IP for h_11 10.0.1.1011" respectively.

**Comment by theojepsen** [comment]
It looks like the bug is here:
https://github.com/p4lang/p4app/blob/master/docker/scripts/mininet/appprocrunner.py#L23

**Comment by theojepsen** [comment]
Thank you for reporting this bug. This PR should fix it https://github.com/p4lang/p4app/pull/47
