### ISSUE TITLE
Enable setting of pcap_dump via target parameters

### ISSUE THREAD

**Issue by gbartl** [p4lang/p4app#45]
single_switch_mininet.py and others have a parameter to enable/disable pcap dump. The README says I should be able to set this field in the target params. The p4apprunner.py doesn't appear to read this from the manifest.target config though and so appears to have no effect.

**Comment by theojepsen** [comment]
Have you checked the the contents of the log directory (`P4APP_LOGDIR`) for the pcap files? This defaults to `/tmp/p4app_logs`. You can also set the log dir through the env, for example:

    P4APP_LOGDIR=out ./p4app run examples/registers.p4app

This will create the directory `out` and store all the files in there. If `"pcap_dump": true`, then the pcaps should also be in the log dir.

When you run p4app, it prints the commands it executes, including starting the switches:

    ...
    simple_switch -i 1@s1-eth1 -i 2@s1-eth2 --pcap --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 router.json --log-console
    ...

Check that it starts the switch with the `--pcap` flag.
