### ISSUE TITLE
Is a directory: '/tmp/app.tar.gz'

### ISSUE THREAD

**Issue by will-gh** [p4lang/p4app#52]
OS: Ubuntu 17.10 VM
p4app up-to-date (13/09/18)
Trying to invoke any of the p4lang/p4app/examples e.g. compile_only.p4app with the p4app 'run' command as: p4app run examples/compile_only.p4app causes the same error message to be shown. 
![p4app](https://user-images.githubusercontent.com/25988198/45479587-cf629580-b73e-11e8-90ac-1650ecbd5c87.PNG)

The compile_only.p4 code run is exactly as it is on p4lang/p4app/examples. 

Any help would be apprectiated, thanks.

**Comment by will-gh** [comment]
For some reason, doing a clean re-install fixed this issue.

**Comment by BerZerKku** [comment]
I have this error too. 
After reinstalling Docker the error disappears. But if I reboot system it comes back.
