### ISSUE TITLE
P4app can't import pycrptodome

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/p4app#67]
I am running a program in p4app that imports pycryptodome but this is the error I'm getting `from Crypto.Hash import MD5\nImportError: No module named Crypto.Hash\n'`. It seems that p4app can't import the pycryptodome library. Does the p4app support it?

system:
windows 8.1 and 10
ubuntu 16.04

**Comment by jnfoster** [comment]
Have you tried rebuilding the Docker container with this library pre-installed?

**Comment by Juniortheone** [comment]
Yes I did but it isn't working. I actually pre-installed the library, tested it before installing the Docker container. Unfortunately, the outcome was the same.

**Comment by jnfoster** [comment]
Sorry, I meant have you tried updating the Docker scripts so the library is pre-installed *within* the container (not the host system).

**Comment by Juniortheone** [comment]
No I haven't. I will search on how to do that and will let you know the outcome. Thank you.

**Comment by Juniortheone** [comment]
@jnfoster How can I update the Docker script? I searched online and what I'm getting is to create a new Docker container. Is that it?

**Comment by Juniortheone** [comment]
@jnfoster Please ignore the earlier message. I found something out and I tried but it did not work. I modified the Dockerfile to this `# Install pycryptodome.
COPY docker/third-party/pycryptodome /third-party/pycryptodome
WORKDIR /third-party/pycryptodome
RUN cp util/m /usr/local/bin/m
RUN make install && \
    rm -rf /third-party/pycryptodome` calling `pip` to install.

**Comment by Juniortheone** [comment]
Can anyone help, please?

**Comment by jnfoster** [comment]
Not sure. Are you sure your `p4app` container is up to date (by running`p4app update`)?

From the above description, it looks like you were trying to install from source. How about adding a line to the Dockerfile to `pip  install pycryptodome` with appropriate options for the version of Python?

Failing that, perhaps @theojepsen can take a look?

**Comment by theojepsen** [comment]
When you run p4app, it launches a Docker container and runs your scripts inside this Docker container. As @jnfoster mentioned, you need to install your dependencies *inside* the p4app Docker image.

@Juniortheone did you rebuild the Docker image after modifying the Dockerfile? You should run `docker build` inside the p4app repo directory. e.g.

    cd p4app
    docker build -t p4lang/p4app .

Optionally, you can also create a Docker image with a new name (instead of `p4lang/p4app`), and specify that Docker image when running p4app. From the README:
https://github.com/p4lang/p4app#advanced-features

    P4APP_IMAGE=me/my_p4app_image:latest p4app run examples/simple_router.p4app

**Comment by Juniortheone** [comment]
Thank you guys for your response. I really appreciate it. @jnfoster I run the update using `p4app update`. @theojepsen I failed to rebuild the Docker image after adding the dependencies. I will try and give a feedback.

**Comment by Juniortheone** [comment]
Thank you @jnfoster @theojepsen. I was able to install the library but the new Dockerfile failed to build. With four more steps to go, I got this error `cp: cannot stat 'util/m': No such file or directory
The command '/bin/sh -c cp util/m /usr/local/bin/m' returned a non-zero code: 1`. To my understanding, this has something to do with the directories when an error is made in the filename or something. This error was generated from the Mininet install command in the Dockerfile but this wasn't changed.I created `m directory` in `/usr/local/bin` since it did not exist. The issue is that `util/m` is non-existent and hence, nothing to copy.

**Comment by theojepsen** [comment]
@Juniortheone did you clone the repo's submodules? i.e.

     git submodule update --init --recursive

**Comment by Juniortheone** [comment]
Yes

**Comment by theojepsen** [comment]
Are you able to build the Docker image before making any changes to the Dockerfile? I tried just now, and was able to clone the repo, init the submodules and run `docker build` without any problems. You should not have to change any parts of the Dockerfile related to setting up Mininet (i.e. do not create an `m` directory).

**Comment by Juniortheone** [comment]
Thank you @theojepsen. I created a fresh OS install and it worked. I'm grateful.
