### ISSUE TITLE
p4app can't compile

### ISSUE THREAD

**Issue by prince901** [p4lang/p4app#70]
I tried running `simple_router.p4app` and `multiswitch.p4app` but they couldn't compile. `simple_counter.p4app` was able to compile though.This was the error
`Entering build directory.
Extracting package.
> touch /tmp/p4app_logs/p4s.s1.log
> ln -s /tmp/p4app_logs/p4s.s1.log /tmp/p4s.s1.log
Reading package manifest.
> p4c-bm2-ss --p4v 16 "simple_router.p4" -o "simple_router.json"
simple_router.p4(12): [--Wwarn=deprecated] warning: mark_to_drop: Using deprecated feature mark_to_drop. Please use mark_to_drop(standard_metadata) instead.
        mark_to_drop();
        ^^^^^^^^^^^^
/usr/local/share/p4c/p4include/v1model.p4(289)
extern void mark_to_drop();
            ^^^^^^^^^^^^
simple_router.p4(35): [--Wwarn=deprecated] warning: mark_to_drop: Using deprecated feature mark_to_drop. Please use mark_to_drop(standard_metadata) instead.
        mark_to_drop();
        ^^^^^^^^^^^^
/usr/local/share/p4c/p4include/v1model.p4(289)
extern void mark_to_drop();
            ^^^^^^^^^^^^
simple_router.p4(12): [--Werror=target-error] error: mark_to_drop: Unsupported on target Expected 1 argument for mark_to_drop. Are you using an up-to-date v1model.p4?
        mark_to_drop();
        ^^^^^^^^^^^^^^
simple_router.p4(35): [--Werror=target-error] error: mark_to_drop: Unsupported on target Expected 1 argument for mark_to_drop. Are you using an up-to-date v1model.p4?
        mark_to_drop();
        ^^^^^^^^^^^^^^
Compile failed.
`
I already updated the p4app and did the same for the path.
System: ubuntu 16.04 and 18.04

**Comment by prince901** [comment]
Please, can someone help me? I'm new to p4 and from the error I know the indicated lines should be changed so I tried reading the P4 specification and used new drop rules using metadata but it still wouldn't compile. `standard_metadata_t standard_metadata) {
    action drop() {
        mark_to_drop();`

**Comment by Polly2014** [comment]
I just met same problem, have you solved it?

**Comment by Polly2014** [comment]
I have soled it, just as the report info says:
 open the ```simple_router.p4``` file, and then replace ```mark_to_drop()``` to ```mark_to_drop(standard_metadata)``` in line 12, 35
Then is runs OK
